### ISSUE TITLE
Testing use case guide

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/asgi-lifespan#13]
This package was originally prompted by https://github.com/encode/httpx/issues/350.

The use case was to test a Starlette app by making calls within a lifespan context, e.g.:

```python
# asgi.py
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse

app = Starlette()

@app.route("/")
async def home(request):
    return PlainTextResponse("Hello, world!")
```

```python
# tests.py
import httpx
import pytest
from asgi_lifespan import LifespanManager

from .asgi import app

@pytest.fixture
async def app():
    async with LifespanManager(app):
        yield

@pytest.fixture
async def client(app):
    async with httpx.AsyncClient(app=app) as client:
        yield client

@pytest.mark.asyncio
async def test_app(client):
    r = await client.get("http://testserver")
    assert r.status_code == 200
    assert r.text == "Hello, world!"
```

We should add a section to the documentation on how to use `asgi-lifespan` in this use case.

**Comment by euri10** [comment]
I switched all my tests cases to httpx Asynclient and use the asgi-lifespan, it's great.

I dont know how others are operating but most of the time I'm using relative urls in my tests, so in the example above would be something like:

```diff
15c15
<     async with httpx.AsyncClient(app=app) as client:
---
>     async with httpx.AsyncClient(app=app, base_url"http://testserver") as client:
20c20,21
<     r = await client.get("http://testserver")
---
>     url = url_path_for("home")
>     r = await client.get(url)
➜  ~

```

**Comment by florimondmanca** [comment]
Glad to know you’ve been using this library with HTTPX! I’ve also been using the `base_url` pattern, very handy. (Though I’m not sure it’s particularly related to `asgi-lifespan`.)

The example pytest setup in the issue description is a bit outdated, now...

- Drop the decorators on the example app, as encouraged with Starlette 0.13+.
- Register lifespan event handles on the app, and include the pytest output to show when handlers are running (ie when preparing the `app` fixture).
- We could actually merge the `app` and `client` fixtures into a single `client` fixture, as in general we don’t need to tap into the app itself when testing it as an “HTTP black box”.

**Comment by euri10** [comment]
everything below is absolutely correct, yet ymmv @florimondmanca : some examples beow

> * Drop the decorators on the example app, as encouraged with Starlette 0.13+.

in my case I'm using FastAPi which still has the decorator syntax

> * We could actually merge the `app` and `client` fixtures into a single `client` fixture, as in general we don’t need to tap into the app itself when testing it as an “HTTP black box”.

I need 2 different fixtures as the app in my case is built in a `get_app` function passing some app_settings parameters, and I want to be able to test different settings. Maybe there's a better layout !

```
@pytest.fixture(scope="session")
async def app_test(monkeypatch_session: MonkeyPatch) -> AsyncIterator[FastAPI]:
    logger.debug("app_test")
    get_app_settings.cache_clear()
    monkeypatch_session.setenv(
        "APP_DEBUG", "True",
    )

    app_settings = get_app_settings()
    app = get_app(app_settings)
    logger.debug("yield app_test")
    async with LifespanManager(app):
        yield app
    logger.debug("end yield app_test")
    logger.debug("end app_test")


@pytest.fixture(scope="session")
async def client(app_test: FastAPI) -> AsyncIterator[AsyncClient]:
    async with httpx.AsyncClient(app=app_test, base_url="http://testserver") as client:
        yield client
```
