### ISSUE TITLE
Can't use LifespanManager with pytest-asyncio

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/asgi-lifespan#15]
Related to https://github.com/agronholm/anyio/issues/74

```python
from asgi_lifespan import LifespanManager, Lifespan
import pytest


@pytest.fixture
async def app():
    app = Lifespan()
    async with LifespanManager(app):
        yield app


@pytest.mark.asyncio
async def test_something(app):
    pass
```

Running `pytest tests.py` fails with a `KeyError`.

This is an issue with `anyio` that is being resolved — tracking here for clarity.

**Comment by JayH5** [comment]
anyio 1.2.0 was released recently and this seems to be fixed

**Comment by florimondmanca** [comment]
Yup, it seems so! 🎉
