### ISSUE TITLE
Should we get rid of `Lifespan` and `LifespanMiddleware`?

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/asgi-lifespan#25]
Currently this package provides three components…

- `Lifespan`: an ASGI app that acts as a container of startup/shutdown event handlers.
- `LifespanMiddleware`: routes `lifespan` requests to a `Lifespan` app, used to add lifespan support to any ASGI app.
- `LifespanManager`: sends lifespan events into an ASGI app.

`LifespanManager` is obviously useful, as it's addressing a use case that's not addressed elsewhere — sending lifespan events into an app, with async support. (Starlette does this with its `TestClient`, but it's sync only, and HTTPX does not send lifespan events when calling into an ASGI app.)

I'm less confident that `Lifespan` and `LifespanMiddleware` are worth keeping in here, though. Most ASGI frameworks provide a lifespan implementation anyway…

Eg. Starlette essentially has the exact same code than our own `Lifespan` built into its router:

https://github.com/encode/starlette/blob/6a65461c6e13d0a55243c19ce5580b1b5a65a770/starlette/routing.py#L508-L527

The super-light routing provided by our `LifespanMiddleware` is built into the router as well:

https://github.com/encode/starlette/blob/6a65461c6e13d0a55243c19ce5580b1b5a65a770/starlette/routing.py#L529-L540

So I'm wondering if using these two components on their own own is a use case that people encounter in the wild. I think it's not, and that maybe we should drop them and point people at using Starlette for handling lifespan on the application side.

**Comment by florimondmanca** [comment]
Personally, I've only used this package to use `LifespanManager` alongside HTTPX for testing ASGI apps.

@euri10 described this use case in https://github.com/florimondmanca/asgi-lifespan/issues/13#issuecomment-578485649 as well.

So… are `Lifespan` and `LifespanMiddleware` not actually useful in practice?

**Comment by florimondmanca** [comment]
Essentially we'd end up with this package being advertised as "`asgi-lifespan`: Send lifespan events into ASGI apps".

**Comment by florimondmanca** [comment]
Note that this would make https://github.com/florimondmanca/asgi-lifespan/issues/22 stale. That issue is a good example that we're actually following what Starlette does with its lifespan API, so we're definitely better off leaving it there…

**Comment by euri10** [comment]
> Personally, I've only used this package to use `LifespanManager` alongside HTTPX for testing ASGI apps.
> 
> @euri10 described this use case in [#13 (comment)](https://github.com/florimondmanca/asgi-lifespan/issues/13#issuecomment-578485649) as well.
> 
> So… are `Lifespan` and `LifespanMiddleware` not actually useful in practice?

my 2 cts, since they seem "built-in" into frameworks that may be the case, however pure-asgi apps if people write them may still love the implementation

**Comment by euri10** [comment]
https://github.com/encode/starlette/pull/799 will likely change starlette lifespan handler implementation, question is how this package interacts with it once the lifespan part does different things ?

**Comment by florimondmanca** [comment]
> https://github.com/encode/starlette/pull/799 will likely change starlette lifespan handler implementation, question is how this package interacts with it once the lifespan part does different things ?

Well, in theory it shouldn't change anything on our side. Any user that uses our `Lifespan` should be able to continue to do so even if they use some Starlette components in the way… But I think it doesn't make much sense for those users to add another dependency to benefit from something that Starlette has built-in, right?

I think my gut-feeling answer to

> if people write them

is that *they don't*. Eg `tartiflette-asgi` uses Starlette's `Lifespan` and `Router` (now merged into one believe) for the implementation of [`TartifletteApp`](https://github.com/tartiflette/tartiflette-asgi/blob/master/tartiflette_asgi/app.py). Even if I didn't use the `Router`, I'd certainly use Starlette's lifespan implementation because I could just reach out to the other ASGI stuff built into Starlette (e.g. its `types` module that's very useful for type hints).

So I'm starting to be a "yes" on this question here — no need to duplicate functionality.

I think a fair plan would be to issue a down-scoped, rebranded 1.0 release of this package with just `LifespanManager`, and point people at Starlette if they want application-side lifespan support.

**Comment by euri10** [comment]
> Well, in theory it shouldn't change anything on our side. Any user that uses our `Lifespan` should be able to continue to do so even if they use some Starlette components in the way… But I think it doesn't make much sense for those users to add another dependency to benefit from something that Starlette has built-in, right?

I'm not sure of this but let's try to phrase it as best as I can: if Starlette's lifespan implementation (then subsequently FastAPI one) uses this new yield approach, and this package doesn't, won't we have an issue in tests using httpx+LifeSpanManager where the tests won't behave the same way the app does ?


> I think a fair plan would be to issue a down-scoped, rebranded 1.0 release of this package with just LifespanManager, and point people at Starlette if they want application-side lifespan support.
agreed 100% !

**Comment by florimondmanca** [comment]
> won't we have an issue in tests using httpx+LifeSpanManager where the tests won't behave the same way the app does ?

We shouldn’t, no, because we’re all based on the ASGI spec. Starlette switching to a yield API doesn’t change the contents and order of the ASGI messages that it will respond to/send back. So we `LifespanManager` should be fine. :)
