### ISSUE TITLE
Rationale for strong dependency on starlette 0.13?

### ISSUE THREAD

**Issue by Lawouach** [florimondmanca/asgi-lifespan#31]
Hello,

I think this is an awesome project. However, the strong dependency on starlette 0.13 makes my test hang forever (I haven't upgrade my code to 0.13 yet so I guess that's that...). Using starlette 0.12 doesn't cause an issue as far as I can tell with this plugin. So, I wondered about the rationale for such strict dependency?

As it stands, I had to drop the plugin when I wanted to migrate all my tests to it :(

Thanks,
- Sylvain

**Comment by florimondmanca** [comment]
Hi!

Which version of this package were you using? As of 1.0 there is no dependency on Starlette anymore. :) (At least, judging from master.)

**Comment by Lawouach** [comment]
The latest I guess. But the dependency is part of the requirements.txt file :) 

https://github.com/florimondmanca/asgi-lifespan/blob/master/requirements.txt

**Comment by florimondmanca** [comment]
The `requirements.txt` file is for development dependencies only (Starlette is used for testing). Runtime dependencies are specified in `setup.py`, and Starlette is not in there. :-)

So at this point I'm thinking
I wasn't able to reproduce the hang on the following minimal setup, maybe this is a proper bug related to some specifics in your project?

```python
import asyncio
from asgi_lifespan import LifespanManager
from starlette.applications import Starlette

app = Starlette(
    on_startup=[lambda: print("startup")], on_shutdown=[lambda: print("shutdown")]
)

async def main():
    async with LifespanManager(app):
        pass

asyncio.run(main())
```

```console
$ pip install "starlette==0.12.*" "asgi-lifespan==1.*"
$ python example.py
startup
shutdown
```

**Comment by Lawouach** [comment]
Yeap, feel free to close it actually.

I have a fairly large testsuite so there is likely some other stuff going on here.

Cheers for responding fast :)
